name: cse571a3
channels:
  - defaults
dependencies:
  - python=3.8.16
  - pip:
    - cython==0.29.34
    - gym==0.19.0
    - gym-notices==0.0.8
    - matplotlib==3.7.1
    - mujoco-py==2.1.2.14
    - numpy==1.24.3
    - packaging==23.1
    - pybullet==3.2.5
    - torch
    - torchvision
    - torchaudio